In [8]:
#!pip install jupyter-datatables
import pandas as pd
# from jupyter_datatables import init_datatables_mode

# # Load the jupyter_require extension
# %load_ext jupyter_require
# init_datatables_mode()

In [9]:
# Import raw data
data = pd.read_csv("../historic_appts_trans.csv")
data

/var/folders/0t/dc47jt692_qc1qb7bqkgylhw0000gn/T/ipykernel_50044/1461436612.py:2: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../historic_appts_trans.csv")

,appointment_id,age_deid,bmi_deid,ethnicity,ethnic_category_black,ethnic_category_unknown,gender_male,imd19_quintile,main_spoken_language_other,current_smoker,...,prediction_type,case_control,use_case,appt_date,appt_month_trans,hospital_service_display_trans,service_mapping_trans,reason_display_trans,appointment_type_trans,did_not_attend_risk_group_trans
0,10079786,52,27.45,NaN,0,1,1,2,0,0,...,First prediction,1.0,3,2024-03-20,3.0,15,2,76,0,3
1,10079786,52,39.45,NaN,1,0,0,2,0,0,...,Last prediction,1.0,3,2024-03-20,3.0,15,2,76,0,3
2,10164094,52,27.45,NaN,1,0,1,2,0,1,...,Last prediction,1.0,3,2023-11-24,11.0,71,2,376,0,2
3,10164094,52,27.45,NaN,1,0,1,2,0,1,...,First prediction,1.0,3,2023-11-24,11.0,71,2,376,0,3
4,10211058,32,39.45,NaN,0,1,0,2,0,0,...,First prediction,1.0,3,2024-01-19,1.0,71,2,376,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278794,13390142,17,27.45,NaN,1,0,1,3,0,0,...,Last prediction,1.0,3,2024-03-11,3.0,95,8,452,0,3
278795,13440971,77,21.70,NaN,0,1,1,2,0,0,...,First prediction,1.0,3,2024-03-20,3.0,36,2,215,1,2
278796,13440971,77,21.70,NaN,0,1,1,2,0,0,...,Last prediction,1.0,3,2024-03-20,3.0,36,2,215,1,1
278797,13463451,52,27.45,NaN,1,0,1,2,0,0,...,First prediction,1.0,3,2024-01-30,1.0,133,10,746,1,3
278798,13463451,52,27.45,NaN,1,0,1,2,0,0,...,Last prediction,1.0,3,2024-01-30,1.0,133,10,746,1,3

In [10]:
# Keep appointments with 'First prediction' (because 'Last prediction' is 'future' behaviour)
first_pred = data[data['prediction_type'] == 'First prediction']
first_pred

,appointment_id,age_deid,bmi_deid,ethnicity,ethnic_category_black,ethnic_category_unknown,gender_male,imd19_quintile,main_spoken_language_other,current_smoker,...,prediction_type,case_control,use_case,appt_date,appt_month_trans,hospital_service_display_trans,service_mapping_trans,reason_display_trans,appointment_type_trans,did_not_attend_risk_group_trans
0,10079786,52,27.45,NaN,0,1,1,2,0,0,...,First prediction,1.0,3,2024-03-20,3.0,15,2,76,0,3
3,10164094,52,27.45,NaN,1,0,1,2,0,1,...,First prediction,1.0,3,2023-11-24,11.0,71,2,376,0,3
4,10211058,32,39.45,NaN,0,1,0,2,0,0,...,First prediction,1.0,3,2024-01-19,1.0,71,2,376,0,1
6,10550310,72,39.45,NaN,1,0,1,4,0,0,...,First prediction,1.0,3,2024-01-19,1.0,71,2,376,0,1
8,10670198,32,39.45,NaN,1,0,0,2,0,1,...,First prediction,1.0,3,2023-12-01,12.0,71,2,376,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278790,13147714,2,27.45,NaN,0,0,0,1,0,0,...,First prediction,1.0,3,2023-12-29,12.0,95,8,499,0,2
278791,13257461,67,40.00,NaN,0,0,0,1,0,0,...,First prediction,1.0,3,2024-02-01,2.0,125,2,694,0,2
278793,13390142,17,27.45,NaN,1,0,1,3,0,0,...,First prediction,1.0,3,2024-03-11,3.0,95,8,452,0,3
278795,13440971,77,21.70,NaN,0,1,1,2,0,0,...,First prediction,1.0,3,2024-03-20,3.0,36,2,215,1,2
278797,13463451,52,27.45,NaN,1,0,1,2,0,0,...,First prediction,1.0,3,2024-01-30,1.0,133,10,746,1,3

In [11]:
# Export data to CSV
first_pred.to_csv("../historic_first_pred.csv", index=False)