In [8]:
import pandas as pd
from sklearn import preprocessing

In [20]:
# Import raw data
data = pd.read_csv("../de_id_data.csv")
data

/var/folders/0t/dc47jt692_qc1qb7bqkgylhw0000gn/T/ipykernel_46377/199410331.py:2: DtypeWarning: Columns (3,13,14,15,18,19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("de_id_data.csv")

,appointment_id,age_deid,bmi_deid,ethnicity,ethnic_category_black,ethnic_category_unknown,gender_male,imd19_quintile,main_spoken_language_other,current_smoker,...,service_mapping_paeds,service_mapping_priority,service_mapping_surgical,weekswaiting,no_show,did_not_attend_risk,did_not_attend_risk_group,prediction_type,case_control,use_case
0,10037229,12,27.45,NaN,0,0,1,4,0,1,...,1,0,0,NaN,1.0,0.172123,Moderate Risk,NaN,0.0,3
1,10079786,52,27.45,NaN,0,1,1,2,0,0,...,0,0,0,NaN,0.0,0.264963,High Risk,First prediction,1.0,3
2,10079786,52,39.45,NaN,1,0,0,2,0,0,...,0,0,0,NaN,0.0,0.197289,High Risk,Last prediction,1.0,3
3,10098651,7,27.45,NaN,1,0,0,2,0,0,...,1,0,0,NaN,0.0,0.298824,High Risk,NaN,0.0,3
4,10112206,22,18.00,NaN,0,0,0,2,1,1,...,0,0,0,NaN,0.0,0.244291,High Risk,NaN,0.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473151,9681649,7,27.45,NaN,0,0,1,1,0,0,...,1,0,0,NaN,1.0,0.159138,Moderate Risk,NaN,0.0,3
473152,9690482,27,27.45,NaN,0,0,1,3,0,0,...,0,0,0,NaN,0.0,0.233454,High Risk,NaN,0.0,3
473153,9802832,72,27.45,NaN,0,0,0,4,0,0,...,0,0,1,NaN,1.0,0.227199,High Risk,NaN,0.0,3
473154,9812003,27,27.45,NaN,1,0,0,2,0,0,...,0,0,0,NaN,0.0,0.128577,Moderate Risk,NaN,0.0,3
473155,9867752,47,27.45,NaN,0,0,0,4,0,0,...,0,0,0,NaN,1.0,0.142699,Moderate Risk,NaN,0.0,3

### Split out data for use case 1

In [76]:
# Split out data for use case 1
useCase1 = data.loc[data["use_case"]  == 1]
useCase1

,appointment_id,age_deid,bmi_deid,ethnicity,ethnic_category_black,ethnic_category_unknown,gender_male,imd19_quintile,main_spoken_language_other,current_smoker,...,service_mapping_paeds,service_mapping_priority,service_mapping_surgical,weekswaiting,no_show,did_not_attend_risk,did_not_attend_risk_group,prediction_type,case_control,use_case
7743,14943511,32,27.45,Asian,0,0,1,2,0,0,...,0,0,0,58.0,NaN,0.287193,High Risk,NaN,NaN,1
22663,15742730,42,27.45,Not Recorded/Stated,0,1,0,1,0,0,...,0,0,0,5.0,NaN,0.351414,High Risk,NaN,NaN,1
117405,16778162,22,21.70,White,0,0,0,2,0,0,...,0,0,1,67.0,NaN,0.575675,Very High Risk,NaN,NaN,1
145864,16994098,32,39.45,Not Recorded/Stated,0,1,0,2,0,0,...,0,0,0,63.0,NaN,0.150000,Moderate Risk,NaN,NaN,1
152481,17047096,62,27.45,Not Recorded/Stated,0,0,1,1,0,0,...,0,0,0,62.0,NaN,0.340443,High Risk,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473107,20254158,32,21.70,White,0,0,1,3,0,0,...,0,0,0,4.0,NaN,0.365332,High Risk,NaN,NaN,1
473108,20254160,82,27.45,Black,1,0,0,2,0,0,...,0,0,0,4.0,NaN,0.088879,Low Risk,NaN,NaN,1
473109,20254163,82,27.45,Black,1,0,0,1,0,1,...,0,0,0,6.0,NaN,0.102636,Low Risk,NaN,NaN,1
473112,20283951,32,27.45,Not Recorded/Stated,0,1,1,2,0,0,...,0,0,0,3.0,NaN,0.111294,Moderate Risk,NaN,NaN,1
473113,20285444,22,21.70,White,0,0,0,1,0,0,...,0,0,0,61.0,NaN,0.167696,Moderate Risk,NaN,NaN,1

In [77]:
# Export data before transformation
useCase1.to_csv("../useCase1_raw.csv", index=False)

### Transform categorical data to numeric data

In [78]:
useCase1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15841 entries, 7743 to 473113
Data columns (total 57 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   appointment_id                        15841 non-null  int64
 1   age_deid                              15841 non-null  int64
 2   bmi_deid                              15841 non-null  float64
 3   ethnicity                             15841 non-null  object
 4   ethnic_category_black                 15841 non-null  int64
 5   ethnic_category_unknown               15841 non-null  int64
 6   gender_male                           15841 non-null  int64
 7   imd19_quintile                        15841 non-null  int64
 8   main_spoken_language_other            15841 non-null  int64
 9   current_smoker                        15841 non-null  int64
 10  substance_misuse                      15841 non-null  int64
 11  smoking_unknown                       15841 non-null  int64
 12  referral_to_treatment_period_status   0 non-null      float64
 13  tfc_name                              15841 non-null  object
 14  patient_on_multiple_pathways          15841 non-null  object
 15  appt_month                            15841 non-null  object
 16  appt_hour                             15841 non-null  float64
 17  appt_duration                         15841 non-null  float64
 18  hospital_service_display              15838 non-null  object
 19  service_mapping                       15841 non-null  object
 20  reason_display                        15841 non-null  object
 21  appointment_type                      15841 non-null  object
 22  new_appt_flag                         15841 non-null  int64
 23  appointment_type_telephone            15841 non-null  int64
 24  appt_hour_11am_to_12pm                15841 non-null  int64
 25  appt_hour_12pm_to_1pm                 15841 non-null  int64
 26  appt_hour_2pm_to_3pm                  15841 non-null  int64
 27  appt_season_winter                    15841 non-null  int64
 28  days_last_appt                        15841 non-null  int64
 29  emergency_enc_last_12m_one_or_two     15841 non-null  int64
 30  emergency_enc_last_12m_three_or_more  15841 non-null  int64
 31  lead_time                             15841 non-null  int64
 32  ltc_count                             15841 non-null  int64
 33  ns_rate_seq                           15841 non-null  float64
 34  num_reschedules_one                   15841 non-null  int64
 35  num_reschedules_two_or_more           15841 non-null  int64
 36  op_appts_last_12m                     15841 non-null  int64
 37  osrm_drive_time                       15841 non-null  float64
 38  other_vulnerability                   15841 non-null  int64
 39  past_no_show_count_one                15841 non-null  int64
 40  past_no_show_count_three_or_more      15841 non-null  int64
 41  past_no_show_count_two                15841 non-null  int64
 42  past_no_show_rate                     15841 non-null  float64
 43  phone_number                          15841 non-null  int64
 44  physically_inactive                   15841 non-null  int64
 45  safeguarding                          15841 non-null  int64
 46  service_mapping_allied_hcp_therapy    15841 non-null  int64
 47  service_mapping_paeds                 15841 non-null  int64
 48  service_mapping_priority              15841 non-null  int64
 49  service_mapping_surgical              15841 non-null  int64
 50  weekswaiting                          15841 non-null  float64
 51  no_show                               0 non-null      float64
 52  did_not_attend_risk                   15841 non-null  float64
 53  did_not_attend_risk_group             15841 non-null  object
 54  prediction_type                       0 non-null      object
 55  case_control                          0 non-null      float64
 56  use_case                              15841 non-null  int64
dtypes: float64(11), int64(36), object(10)
memory usage: 7.0+ MB

In [79]:
# Encode the ethnicity column

# Create a label encoder object
le = preprocessing.LabelEncoder()

# Fit the label encoder
label = le.fit_transform(useCase1["ethnicity"])

# Add the encoded column to the data
useCase1["ethnicity_trans"] = label

useCase1

/var/folders/0t/dc47jt692_qc1qb7bqkgylhw0000gn/T/ipykernel_46377/4073254805.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  useCase1["ethnicity_trans"] = label

,appointment_id,age_deid,bmi_deid,ethnicity,ethnic_category_black,ethnic_category_unknown,gender_male,imd19_quintile,main_spoken_language_other,current_smoker,...,service_mapping_priority,service_mapping_surgical,weekswaiting,no_show,did_not_attend_risk,did_not_attend_risk_group,prediction_type,case_control,use_case,ethnicity_trans
7743,14943511,32,27.45,Asian,0,0,1,2,0,0,...,0,0,58.0,NaN,0.287193,High Risk,NaN,NaN,1,0
22663,15742730,42,27.45,Not Recorded/Stated,0,1,0,1,0,0,...,0,0,5.0,NaN,0.351414,High Risk,NaN,NaN,1,3
117405,16778162,22,21.70,White,0,0,0,2,0,0,...,0,1,67.0,NaN,0.575675,Very High Risk,NaN,NaN,1,5
145864,16994098,32,39.45,Not Recorded/Stated,0,1,0,2,0,0,...,0,0,63.0,NaN,0.150000,Moderate Risk,NaN,NaN,1,3
152481,17047096,62,27.45,Not Recorded/Stated,0,0,1,1,0,0,...,0,0,62.0,NaN,0.340443,High Risk,NaN,NaN,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473107,20254158,32,21.70,White,0,0,1,3,0,0,...,0,0,4.0,NaN,0.365332,High Risk,NaN,NaN,1,5
473108,20254160,82,27.45,Black,1,0,0,2,0,0,...,0,0,4.0,NaN,0.088879,Low Risk,NaN,NaN,1,1
473109,20254163,82,27.45,Black,1,0,0,1,0,1,...,0,0,6.0,NaN,0.102636,Low Risk,NaN,NaN,1,1
473112,20283951,32,27.45,Not Recorded/Stated,0,1,1,2,0,0,...,0,0,3.0,NaN,0.111294,Moderate Risk,NaN,NaN,1,3
473113,20285444,22,21.70,White,0,0,0,1,0,0,...,0,0,61.0,NaN,0.167696,Moderate Risk,NaN,NaN,1,5

In [80]:
# Encode the tfc_name column

# Create a label encoder object
le = preprocessing.LabelEncoder()

# Fit the label encoder
label = le.fit_transform(useCase1["tfc_name"])

# Add the encoded column to the data
useCase1["tfc_name_trans"] = label

/var/folders/0t/dc47jt692_qc1qb7bqkgylhw0000gn/T/ipykernel_46377/1064608810.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  useCase1["tfc_name_trans"] = label

In [81]:
# Encode the patient_on_multiple_pathways column

# Create a label encoder object
le = preprocessing.LabelEncoder()

# Fit the label encoder
label = le.fit_transform(useCase1["patient_on_multiple_pathways"])

# Add the encoded column to the data
useCase1["patient_on_multiple_pathways_trans"] = label

/var/folders/0t/dc47jt692_qc1qb7bqkgylhw0000gn/T/ipykernel_46377/2045222691.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  useCase1["patient_on_multiple_pathways_trans"] = label

In [82]:
# Encode the appt_month column

month_mapping ={
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12
}

# Map the month names to numbers
useCase1["appt_month_trans"] = useCase1["appt_month"].map(month_mapping)

useCase1[['appt_month', 'appt_month_trans']]

/var/folders/0t/dc47jt692_qc1qb7bqkgylhw0000gn/T/ipykernel_46377/3855715047.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  useCase1["appt_month_trans"] = useCase1["appt_month"].map(month_mapping)

       appt_month  appt_month_trans
7743      October                10
22663      August                 8
117405        May                 5
145864       June                 6
152481        May                 5
...           ...               ...
473107  September                 9
473108  September                 9
473109  September                 9
473112       July                 7
473113    October                10

[15841 rows x 2 columns]

In [83]:
# Encode the hospital_service_display column

# Create a label encoder object
le = preprocessing.LabelEncoder()

# Fit the label encoder
label = le.fit_transform(useCase1["hospital_service_display"])

# Add the encoded column to the data
useCase1["hospital_service_display_trans"] = label

/var/folders/0t/dc47jt692_qc1qb7bqkgylhw0000gn/T/ipykernel_46377/4154795017.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  useCase1["hospital_service_display_trans"] = label

In [84]:
# Encode the service_mapping column

# Create a label encoder object
le = preprocessing.LabelEncoder()

# Fit the label encoder
label = le.fit_transform(useCase1["service_mapping"])

# Add the encoded column to the data
useCase1["service_mapping_trans"] = label

/var/folders/0t/dc47jt692_qc1qb7bqkgylhw0000gn/T/ipykernel_46377/3548066655.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  useCase1["service_mapping_trans"] = label

In [85]:
# Encode the reason_display column

# Create a label encoder object
le = preprocessing.LabelEncoder()

# Fit the label encoder
label = le.fit_transform(useCase1["reason_display"])

# Add the encoded column to the data
useCase1["reason_display_trans"] = label

/var/folders/0t/dc47jt692_qc1qb7bqkgylhw0000gn/T/ipykernel_46377/458353874.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  useCase1["reason_display_trans"] = label

In [86]:
# Encode the appointment_type column

# Create a label encoder object
le = preprocessing.LabelEncoder()

# Fit the label encoder
label = le.fit_transform(useCase1["appointment_type"])

# Add the encoded column to the data
useCase1["appointment_type_trans"] = label

/var/folders/0t/dc47jt692_qc1qb7bqkgylhw0000gn/T/ipykernel_46377/2439482386.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  useCase1["appointment_type_trans"] = label

In [87]:
# Encode the did_not_attend_risk_group column

risk_mapping ={
    "Low Risk": 1,
    "Moderate Risk": 2,
    "High Risk": 3,
    "Very High Risk": 4,
}

# Map the month names to numbers
useCase1["did_not_attend_risk_group_trans"] = useCase1["did_not_attend_risk_group"].map(risk_mapping)

useCase1[['did_not_attend_risk_group', 'did_not_attend_risk_group_trans']]

/var/folders/0t/dc47jt692_qc1qb7bqkgylhw0000gn/T/ipykernel_46377/1007344296.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  useCase1["did_not_attend_risk_group_trans"] = useCase1["did_not_attend_risk_group"].map(risk_mapping)

       did_not_attend_risk_group  did_not_attend_risk_group_trans
7743                   High Risk                                3
22663                  High Risk                                3
117405            Very High Risk                                4
145864             Moderate Risk                                2
152481                 High Risk                                3
...                          ...                              ...
473107                 High Risk                                3
473108                  Low Risk                                1
473109                  Low Risk                                1
473112             Moderate Risk                                2
473113             Moderate Risk                                2

[15841 rows x 2 columns]

In [88]:
useCase1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15841 entries, 7743 to 473113
Data columns (total 66 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   appointment_id                        15841 non-null  int64
 1   age_deid                              15841 non-null  int64
 2   bmi_deid                              15841 non-null  float64
 3   ethnicity                             15841 non-null  object
 4   ethnic_category_black                 15841 non-null  int64
 5   ethnic_category_unknown               15841 non-null  int64
 6   gender_male                           15841 non-null  int64
 7   imd19_quintile                        15841 non-null  int64
 8   main_spoken_language_other            15841 non-null  int64
 9   current_smoker                        15841 non-null  int64
 10  substance_misuse                      15841 non-null  int64
 11  smoking_unknown                       15841 non-null  int64
 12  referral_to_treatment_period_status   0 non-null      float64
 13  tfc_name                              15841 non-null  object
 14  patient_on_multiple_pathways          15841 non-null  object
 15  appt_month                            15841 non-null  object
 16  appt_hour                             15841 non-null  float64
 17  appt_duration                         15841 non-null  float64
 18  hospital_service_display              15838 non-null  object
 19  service_mapping                       15841 non-null  object
 20  reason_display                        15841 non-null  object
 21  appointment_type                      15841 non-null  object
 22  new_appt_flag                         15841 non-null  int64
 23  appointment_type_telephone            15841 non-null  int64
 24  appt_hour_11am_to_12pm                15841 non-null  int64
 25  appt_hour_12pm_to_1pm                 15841 non-null  int64
 26  appt_hour_2pm_to_3pm                  15841 non-null  int64
 27  appt_season_winter                    15841 non-null  int64
 28  days_last_appt                        15841 non-null  int64
 29  emergency_enc_last_12m_one_or_two     15841 non-null  int64
 30  emergency_enc_last_12m_three_or_more  15841 non-null  int64
 31  lead_time                             15841 non-null  int64
 32  ltc_count                             15841 non-null  int64
 33  ns_rate_seq                           15841 non-null  float64
 34  num_reschedules_one                   15841 non-null  int64
 35  num_reschedules_two_or_more           15841 non-null  int64
 36  op_appts_last_12m                     15841 non-null  int64
 37  osrm_drive_time                       15841 non-null  float64
 38  other_vulnerability                   15841 non-null  int64
 39  past_no_show_count_one                15841 non-null  int64
 40  past_no_show_count_three_or_more      15841 non-null  int64
 41  past_no_show_count_two                15841 non-null  int64
 42  past_no_show_rate                     15841 non-null  float64
 43  phone_number                          15841 non-null  int64
 44  physically_inactive                   15841 non-null  int64
 45  safeguarding                          15841 non-null  int64
 46  service_mapping_allied_hcp_therapy    15841 non-null  int64
 47  service_mapping_paeds                 15841 non-null  int64
 48  service_mapping_priority              15841 non-null  int64
 49  service_mapping_surgical              15841 non-null  int64
 50  weekswaiting                          15841 non-null  float64
 51  no_show                               0 non-null      float64
 52  did_not_attend_risk                   15841 non-null  float64
 53  did_not_attend_risk_group             15841 non-null  object
 54  prediction_type                       0 non-null      object
 55  case_control                          0 non-null      float64
 56  use_case                              15841 non-null  int64
 57  ethnicity_trans                       15841 non-null  int64
 58  tfc_name_trans                        15841 non-null  int64
 59  patient_on_multiple_pathways_trans    15841 non-null  int64
 60  appt_month_trans                      15841 non-null  int64
 61  hospital_service_display_trans        15841 non-null  int64
 62  service_mapping_trans                 15841 non-null  int64
 63  reason_display_trans                  15841 non-null  int64
 64  appointment_type_trans                15841 non-null  int64
 65  did_not_attend_risk_group_trans       15841 non-null  int64
dtypes: float64(11), int64(45), object(10)
memory usage: 8.1+ MB

### Export the transformed use case 1 data

In [89]:
# Dropped all transformed columns
useCase1_trans = useCase1.drop(["ethnicity",
"tfc_name",
"patient_on_multiple_pathways",
"appt_month",
"hospital_service_display",
"service_mapping",
"reason_display",
"appointment_type",
"did_not_attend_risk_group"], axis =1)

# Export data for use case 1 to CSV
useCase1_trans.to_csv("../useCase1_trans.csv", index=False)